stages:
  - compile
  - build
  - deploy
  - release
  - refresh

variables:
  # CI VARIABLES
  CI_REGISTRY_USER: bkwh-registry
  CI_REGISTRY_PASSWORD: 3eYVgSfPu1YH4xp-XbQ2
  CI_REGISTRY: registry-iconx.air.id
  GITLAB_USER: ci-tag-bot
  GITLAB_TOKEN: us65FqAg2kaazuPWnXKm

  # IMAGE VARIABLES
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

Create Git Tag:
  stage: release
  image: alpine
  before_script:
    - apk add --no-cache git
    - git config --global user.email "devops-master@iconpln.co.id"
    - git config --global user.name "devops-master"
    - git remote set-url origin https://${GITLAB_USER}:${GITLAB_TOKEN}@repo-iconx.air.id/micro-apps/reward-loyalty-microapps-v2.git
  script: |
    git fetch --tags
    LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

    if [ -z "$LAST_TAG" ]; then
      NEW_TAG="0.0.1"
    else
      MAJOR=$(echo $LAST_TAG | cut -d. -f1)
      MINOR=$(echo $LAST_TAG | cut -d. -f2)
      PATCH=$(echo $LAST_TAG | cut -d. -f3)
      NEW_TAG="$MAJOR.$MINOR.$((PATCH+1))"
    fi

    echo "New tag: $NEW_TAG"
    git tag $NEW_TAG
    git push origin $NEW_TAG
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  tags:
    - docker

Compile NPM:
  stage: compile
  image: node:22-alpine
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
  before_script:
    - node --version
    - npm --version
    - npm rebuild node-sass
    - npm install
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "development" ]; then
        npm run build:dev
      else
        npm run build:prod
      fi
  artifacts:
    name: "dist-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - development
    - staging
    - tags
  tags:
    - docker

Build Container:
  stage: build
  image: docker:20.10.5
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --no-cache -t $DOCKER_IMAGE --build-arg DIST_FOLDER=dist -f deploy/Dockerfile .
    - docker push $DOCKER_IMAGE
  only:
    - development
    - staging
    - tags
  tags:
    - docker

# =========================
# UPDATE HELM VALUES (INFRA REPO)
# =========================
Update Helm Values:
  stage: release
  image: alpine:latest
  before_script:
    - apk add --no-cache git yq
    - git config --global user.email "devops-master@iconpln.co.id"
    - git config --global user.name "devops-master"
  script: |
    git clone https://${GITLAB_USER}:${GITLAB_TOKEN}@repo-iconx.air.id/k8s-infra-deployment/k8s-production-all-in-one.git
    cd k8s-production-all-in-one/events/reward-loyalty-v2
    yq -i ".image.tag = \"${CI_COMMIT_TAG}\"" values.yaml
    git add values.yaml
    git commit -m "chore: update rewardloyaltyv2 image to ${CI_COMMIT_TAG}"
    git push origin main
  rules:
    - if: "$CI_COMMIT_TAG"
  tags:
    - docker

Sync App & Refresh App:
  stage: refresh
  script:
    - printf "y\n" | argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
    - argocd app sync events-reward-v2
    - argocd app get events-reward-v2 --refresh
    - argocd logout $ARGOCD_SERVER
  rules:
    - if: "$CI_COMMIT_TAG"
  tags:
    - bkwh-runner

Deploy DevStaging:
  stage: deploy
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "development" ]; then
        kubectl set image deployment/microapps-reward-loyaltyv2 microapps-reward-loyaltyv2=$DOCKER_IMAGE -n development
        kubectl rollout restart deployment/microapps-reward-loyaltyv2 -n development
      else
        kubectl set image deployment/microapps-reward-loyaltyv2 microapps-reward-loyaltyv2=$DOCKER_IMAGE -n staging
        kubectl rollout restart deployment/microapps-reward-loyaltyv2 -n staging
      fi
  only:
    - development
    - staging
  tags:
    - bkwh-runner
