/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(default)': RouteRecordInfo<
      '/(default)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(default)/'
      | '/(default)/eco-journey-points/history'
      | '/(default)/rewards/[id]'
      | '/(default)/rewards/complete-address'
      | '/(default)/rewards/history'
      | '/(default)/rewards/list'
      | '/(default)/rewards/my-rewards'
      | '/(default)/rewards/redemption/[id]'
      | '/(default)/rewards/winners'
    >,
    '/(default)/': RouteRecordInfo<
      '/(default)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/eco-journey-points/history': RouteRecordInfo<
      '/(default)/eco-journey-points/history',
      '/eco-journey-points/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/rewards/[id]': RouteRecordInfo<
      '/(default)/rewards/[id]',
      '/rewards/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(default)/rewards/complete-address': RouteRecordInfo<
      '/(default)/rewards/complete-address',
      '/rewards/complete-address',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/rewards/history': RouteRecordInfo<
      '/(default)/rewards/history',
      '/rewards/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/rewards/list': RouteRecordInfo<
      '/(default)/rewards/list',
      '/rewards/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/rewards/my-rewards': RouteRecordInfo<
      '/(default)/rewards/my-rewards',
      '/rewards/my-rewards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/rewards/redemption/[id]': RouteRecordInfo<
      '/(default)/rewards/redemption/[id]',
      '/rewards/redemption/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(default)/rewards/winners': RouteRecordInfo<
      '/(default)/rewards/winners',
      '/rewards/winners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/demo/(bottom-nav)': RouteRecordInfo<
      '/demo/(bottom-nav)',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | '/demo/(bottom-nav)/'
      | '/demo/(bottom-nav)/dashboard'
      | '/demo/(bottom-nav)/products'
      | '/demo/(bottom-nav)/tabs'
    >,
    '/demo/(bottom-nav)/': RouteRecordInfo<
      '/demo/(bottom-nav)/',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/(bottom-nav)/dashboard': RouteRecordInfo<
      '/demo/(bottom-nav)/dashboard',
      '/demo/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/(bottom-nav)/products': RouteRecordInfo<
      '/demo/(bottom-nav)/products',
      '/demo/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/(bottom-nav)/tabs': RouteRecordInfo<
      '/demo/(bottom-nav)/tabs',
      '/demo/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/examples/example-scrollable-page': RouteRecordInfo<
      '/demo/examples/example-scrollable-page',
      '/demo/examples/example-scrollable-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/examples/login': RouteRecordInfo<
      '/demo/examples/login',
      '/demo/examples/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/examples/products/[id]': RouteRecordInfo<
      '/demo/examples/products/[id]',
      '/demo/examples/products/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/demo/examples/products/search-products': RouteRecordInfo<
      '/demo/examples/products/search-products',
      '/demo/examples/products/search-products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(default).vue': {
      routes:
        | '/(default)'
        | '/(default)/'
        | '/(default)/eco-journey-points/history'
        | '/(default)/rewards/[id]'
        | '/(default)/rewards/complete-address'
        | '/(default)/rewards/history'
        | '/(default)/rewards/list'
        | '/(default)/rewards/my-rewards'
        | '/(default)/rewards/redemption/[id]'
        | '/(default)/rewards/winners'
      views:
        | 'default'
    }
    'src/pages/(default)/index.vue': {
      routes:
        | '/(default)/'
      views:
        | never
    }
    'src/pages/(default)/eco-journey-points/history.vue': {
      routes:
        | '/(default)/eco-journey-points/history'
      views:
        | never
    }
    'src/pages/(default)/rewards/[id].vue': {
      routes:
        | '/(default)/rewards/[id]'
      views:
        | never
    }
    'src/pages/(default)/rewards/complete-address.vue': {
      routes:
        | '/(default)/rewards/complete-address'
      views:
        | never
    }
    'src/pages/(default)/rewards/history.vue': {
      routes:
        | '/(default)/rewards/history'
      views:
        | never
    }
    'src/pages/(default)/rewards/list.vue': {
      routes:
        | '/(default)/rewards/list'
      views:
        | never
    }
    'src/pages/(default)/rewards/my-rewards.vue': {
      routes:
        | '/(default)/rewards/my-rewards'
      views:
        | never
    }
    'src/pages/(default)/rewards/redemption/[id].vue': {
      routes:
        | '/(default)/rewards/redemption/[id]'
      views:
        | never
    }
    'src/pages/(default)/rewards/winners.vue': {
      routes:
        | '/(default)/rewards/winners'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/demo/(bottom-nav).vue': {
      routes:
        | '/demo/(bottom-nav)'
        | '/demo/(bottom-nav)/'
        | '/demo/(bottom-nav)/dashboard'
        | '/demo/(bottom-nav)/products'
        | '/demo/(bottom-nav)/tabs'
      views:
        | 'default'
    }
    'src/pages/demo/(bottom-nav)/index.vue': {
      routes:
        | '/demo/(bottom-nav)/'
      views:
        | never
    }
    'src/pages/demo/(bottom-nav)/dashboard.vue': {
      routes:
        | '/demo/(bottom-nav)/dashboard'
      views:
        | never
    }
    'src/pages/demo/(bottom-nav)/products.vue': {
      routes:
        | '/demo/(bottom-nav)/products'
      views:
        | never
    }
    'src/pages/demo/(bottom-nav)/tabs.vue': {
      routes:
        | '/demo/(bottom-nav)/tabs'
      views:
        | never
    }
    'src/pages/demo/examples/example-scrollable-page.vue': {
      routes:
        | '/demo/examples/example-scrollable-page'
      views:
        | never
    }
    'src/pages/demo/examples/login.vue': {
      routes:
        | '/demo/examples/login'
      views:
        | never
    }
    'src/pages/demo/examples/products/[id].vue': {
      routes:
        | '/demo/examples/products/[id]'
      views:
        | never
    }
    'src/pages/demo/examples/products/search-products.vue': {
      routes:
        | '/demo/examples/products/search-products'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
