/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(app)': RouteRecordInfo<
      '/(app)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(app)/dashboard'
      | '/(app)/monitoring'
      | '/(app)/voucher-submission/'
      | '/(app)/voucher-submission/[id]'
    >,
    '/(app)/dashboard': RouteRecordInfo<
      '/(app)/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/monitoring': RouteRecordInfo<
      '/(app)/monitoring',
      '/monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/voucher-submission/': RouteRecordInfo<
      '/(app)/voucher-submission/',
      '/voucher-submission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(app)/voucher-submission/[id]': RouteRecordInfo<
      '/(app)/voucher-submission/[id]',
      '/voucher-submission/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'PublicVoucherRequest': RouteRecordInfo<
      'PublicVoucherRequest',
      '/voucher-request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/(auth)': RouteRecordInfo<
      '/(auth)',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | 'ForgotPasswordPage'
      | 'LoginPage'
      | 'RegisterPage'
      | 'ResetPasswordPage'
    >,
    'ForgotPasswordPage': RouteRecordInfo<
      'ForgotPasswordPage',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LoginPage': RouteRecordInfo<
      'LoginPage',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'RegisterPage': RouteRecordInfo<
      'RegisterPage',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ResetPasswordPage': RouteRecordInfo<
      'ResetPasswordPage',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs': RouteRecordInfo<
      '/docs',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | '/docs/admin-examples/categories'
      | '/docs/admin-examples/invoices/'
      | '/docs/admin-examples/invoices/[id]'
      | '/docs/admin-examples/orders/'
      | '/docs/admin-examples/orders/[id]'
      | '/docs/admin-examples/orders/new'
      | '/docs/admin-examples/overview'
      | '/docs/admin-examples/products'
      | '/docs/admin-examples/users'
      | '/docs/admin-examples/vouchers'
      | 'FormShowcase'
    >,
    'FormShowcase': RouteRecordInfo<
      'FormShowcase',
      '/docs/form-showcase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/categories': RouteRecordInfo<
      '/docs/admin-examples/categories',
      '/docs/admin-examples/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/invoices/': RouteRecordInfo<
      '/docs/admin-examples/invoices/',
      '/docs/admin-examples/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/invoices/[id]': RouteRecordInfo<
      '/docs/admin-examples/invoices/[id]',
      '/docs/admin-examples/invoices/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/docs/admin-examples/orders/': RouteRecordInfo<
      '/docs/admin-examples/orders/',
      '/docs/admin-examples/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/orders/[id]': RouteRecordInfo<
      '/docs/admin-examples/orders/[id]',
      '/docs/admin-examples/orders/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/docs/admin-examples/orders/new': RouteRecordInfo<
      '/docs/admin-examples/orders/new',
      '/docs/admin-examples/orders/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/overview': RouteRecordInfo<
      '/docs/admin-examples/overview',
      '/docs/admin-examples/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/products': RouteRecordInfo<
      '/docs/admin-examples/products',
      '/docs/admin-examples/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/users': RouteRecordInfo<
      '/docs/admin-examples/users',
      '/docs/admin-examples/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/admin-examples/vouchers': RouteRecordInfo<
      '/docs/admin-examples/vouchers',
      '/docs/admin-examples/vouchers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(app).vue': {
      routes:
        | '/(app)'
        | '/(app)/dashboard'
        | '/(app)/monitoring'
        | '/(app)/voucher-submission/'
        | '/(app)/voucher-submission/[id]'
      views:
        | 'default'
    }
    'src/pages/(app)/dashboard.vue': {
      routes:
        | '/(app)/dashboard'
      views:
        | never
    }
    'src/pages/(app)/monitoring.vue': {
      routes:
        | '/(app)/monitoring'
      views:
        | never
    }
    'src/pages/(app)/voucher-submission/index.vue': {
      routes:
        | '/(app)/voucher-submission/'
      views:
        | never
    }
    'src/pages/(app)/voucher-submission/[id].vue': {
      routes:
        | '/(app)/voucher-submission/[id]'
      views:
        | never
    }
    'src/pages/(public)/voucher-request.vue': {
      routes:
        | 'PublicVoucherRequest'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/(auth).vue': {
      routes:
        | '/(auth)'
        | 'ForgotPasswordPage'
        | 'LoginPage'
        | 'RegisterPage'
        | 'ResetPasswordPage'
      views:
        | 'default'
    }
    'src/pages/(auth)/forgot-password.vue': {
      routes:
        | 'ForgotPasswordPage'
      views:
        | never
    }
    'src/pages/(auth)/login.vue': {
      routes:
        | 'LoginPage'
      views:
        | never
    }
    'src/pages/(auth)/register.vue': {
      routes:
        | 'RegisterPage'
      views:
        | never
    }
    'src/pages/(auth)/reset-password.vue': {
      routes:
        | 'ResetPasswordPage'
      views:
        | never
    }
    'src/pages/docs.vue': {
      routes:
        | '/docs'
        | '/docs/admin-examples/categories'
        | '/docs/admin-examples/invoices/'
        | '/docs/admin-examples/invoices/[id]'
        | '/docs/admin-examples/orders/'
        | '/docs/admin-examples/orders/[id]'
        | '/docs/admin-examples/orders/new'
        | '/docs/admin-examples/overview'
        | '/docs/admin-examples/products'
        | '/docs/admin-examples/users'
        | '/docs/admin-examples/vouchers'
        | 'FormShowcase'
      views:
        | 'default'
    }
    'src/pages/docs/form-showcase.vue': {
      routes:
        | 'FormShowcase'
      views:
        | never
    }
    'src/pages/docs/admin-examples/categories.vue': {
      routes:
        | '/docs/admin-examples/categories'
      views:
        | never
    }
    'src/pages/docs/admin-examples/invoices/index.vue': {
      routes:
        | '/docs/admin-examples/invoices/'
      views:
        | never
    }
    'src/pages/docs/admin-examples/invoices/[id].vue': {
      routes:
        | '/docs/admin-examples/invoices/[id]'
      views:
        | never
    }
    'src/pages/docs/admin-examples/orders/index.vue': {
      routes:
        | '/docs/admin-examples/orders/'
      views:
        | never
    }
    'src/pages/docs/admin-examples/orders/[id].vue': {
      routes:
        | '/docs/admin-examples/orders/[id]'
      views:
        | never
    }
    'src/pages/docs/admin-examples/orders/new.vue': {
      routes:
        | '/docs/admin-examples/orders/new'
      views:
        | never
    }
    'src/pages/docs/admin-examples/overview.vue': {
      routes:
        | '/docs/admin-examples/overview'
      views:
        | never
    }
    'src/pages/docs/admin-examples/products.vue': {
      routes:
        | '/docs/admin-examples/products'
      views:
        | never
    }
    'src/pages/docs/admin-examples/users.vue': {
      routes:
        | '/docs/admin-examples/users'
      views:
        | never
    }
    'src/pages/docs/admin-examples/vouchers.vue': {
      routes:
        | '/docs/admin-examples/vouchers'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
